name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build & Test Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # full history for better versioning/annotations

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: gradle

      - name: Configure Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Clean project
        run: ./gradlew clean

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Upload Test Results
        if: always()  # Upload even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            **/build/test-results/testDebugUnitTest/
            **/build/reports/tests/testDebugUnitTest/
